<a href="https://colab.research.google.com/github/RamyaSri2222/Data-Science/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numerical**

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
df={
    "Company":["Google","Twitter","Google","LinkedIn"],
    "Role":["Data Scientist","Data Analyst","HR","HR"]
    }
df1=pd.DataFrame(df)
print(df1)
model=LabelEncoder()
df1["company1"]=model.fit_transform(df["Company"])
df1["Role1"]=model.fit_transform(df["Role"])

print()
print(df1)

    Company            Role
0    Google  Data Scientist
1   Twitter    Data Analyst
2    Google              HR
3  LinkedIn              HR

    Company            Role  company1  Role1
0    Google  Data Scientist         0      1
1   Twitter    Data Analyst         2      0
2    Google              HR         0      2
3  LinkedIn              HR         1      2


In [ ]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
df={
    "x":[1,2,3,4,5],
    "y":[3,4,1,2,3]
}
df1=pd.DataFrame(df)
print(df1)
model= MinMaxScaler()
df1["x"]=model.fit_transform(df1[["x"]])
df1["y"]=model.fit_transform(df1[["y"]])
print()
print(df1)

   x  y
0  1  3
1  2  4
2  3  1
3  4  2
4  5  3

      x         y
0  0.00  0.666667
1  0.25  1.000000
2  0.50  0.000000
3  0.75  0.333333
4  1.00  0.666667


In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np
a=[[10,20],[30,40],[50,60],[70,80]]
f=np.array(a)

def add_ten(x):
  return x+10
ob=FunctionTransformer(add_ten)
model=ob.transform(f)
print(model)


[[20 30]
 [40 50]
 [60 70]
 [80 90]]


In [ ]:

import numpy as np
import pandas as pd

house=pd.DataFrame()
house["Price"]=[53443,45673,56743,78392]
house["rooms"]=[2,3,2,116]
house["saqure_Feet"]=[1500,2500,1500,4800]
print(house)

   Price  rooms  saqure_Feet
0  53443      2         1500
1  45673      3         2500
2  56743      2         1500
3  78392    116         4800


In [ ]:
import numpy as np
import pandas as pd

house=pd.DataFrame()
house["Price"]=[53443,45673,56743,78392]
house["rooms"]=[2,3,2,116]
house["saqure_Feet"]=[1500,2500,1500,4800]
con1=house["rooms"]<20
new=house[con1]
print(new)

   Price  rooms  saqure_Feet
0  53443      2         1500
1  45673      3         2500
2  56743      2         1500


In [ ]:
import numpy as np
import pandas as pd

house=pd.DataFrame()
house["Price"]=[53443,45673,56743,78392]
house["rooms"]=[2,3,2,116]
house["saqure_Feet"]=[1500,2500,1500,4800]

house["outlier"]=np.where(house["rooms"]<20,0,1)
print(house)

   Price  rooms  saqure_Feet  outlier
0  53443      2         1500        0
1  45673      3         2500        0
2  56743      2         1500        0
3  78392    116         4800        1


In [ ]:
from sklearn.impute import SimpleImputer
import pandas as pd
df=[
    [85,"M","verygood"],
    [95,"F","excellent"],
    [60,"None","good"],
    [np.nan,"M","avrage"],
    [70,"M","good"],
    [np.nan,None,"verygood"],
    [60,"F","verygood"],
    [98,"M","execellent"]
]
cols=["marks","gender","result"]
df2=pd.DataFrame(df,columns=cols)
print(df2)


   marks gender      result
0   85.0      M    verygood
1   95.0      F   excellent
2   60.0   None        good
3    NaN      M      avrage
4   70.0      M        good
5    NaN   None    verygood
6   60.0      F    verygood
7   98.0      M  execellent


In [ ]:
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

df=[
    [85,"M","verygood"],
    [95,"F","excellent"],
    [60,"None","good"],
    [np.nan,"M","avrage"],
    [70,"M","good"],
    [np.nan,None,"verygood"],
    [60,"F","verygood"],
    [98,"M","execellent"]
]
cols=["marks","gender","result"]
df2=pd.DataFrame(df,columns=cols)
print(df2)

model=SimpleImputer(missing_values=np.nan,strategy="constant",fill_value=80)

result = df2["marks"].values.reshape(-1,1)
df2["marks"] = model.fit_transform(result)
print()
print(df2)

   marks gender      result
0   85.0      M    verygood
1   95.0      F   excellent
2   60.0   None        good
3    NaN      M      avrage
4   70.0      M        good
5    NaN   None    verygood
6   60.0      F    verygood
7   98.0      M  execellent

   marks gender      result
0   85.0      M    verygood
1   95.0      F   excellent
2   60.0   None        good
3   80.0      M      avrage
4   70.0      M        good
5   80.0   None    verygood
6   60.0      F    verygood
7   98.0      M  execellent


In [ ]:
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

df=[
    [85,"M","verygood"],
    [95,"F","excellent"],
    [60,"None","good"],
    [np.nan,"M","avrage"],
    [70,"M","good"],
    [np.nan,None,"verygood"],
    [60,"F","verygood"],
    [98,"M","execellent"]
]
cols=["marks","gender","result"]
df2=pd.DataFrame(df,columns=cols)
print(df2)

model=SimpleImputer(missing_values=np.nan,strategy="constant",fill_value=80)

# Corrected: Use df2 instead of df and fix typo fit_tarnsform to fit_transform
result = df2["marks"].values.reshape(-1,1)
df2["marks"] = model.fit_transform(result)
print()
print(df2)

**Categorical**

In [3]:
from sklearn.preprocessing import OrdinalEncoder
from numpy import asarray
df=asarray([["blue"],["green"],["red"]])
encoder=OrdinalEncoder()
model=encoder.fit_transform(df)
print(model)

[[0.]
 [1.]
 [2.]
 [3.]]


In [15]:
from sklearn.preprocessing import OneHotEncoder
from numpy import asarray
df=asarray([["blue"],["green"],["red"]])
encoder=OneHotEncoder(sparse_output=False)
model=encoder.fit_transform(df)
print(model)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
from sklearn.preprocessing import OneHotEncoder
from numpy import asarray
df=asarray([["apple"],["banana"],["peer"],["apple"]])
encoder=OneHotEncoder(sparse_output=False)
model=encoder.fit_transform(df)
print(model)


[[0. 0.]
 [1. 0.]
 [0. 1.]
 [0. 0.]]


In [17]:
from sklearn.preprocessing import OneHotEncoder
from numpy import asarray
df=asarray([["apple"],["banana"],["peer"],["apple"]])
encoder=OneHotEncoder(drop="first",sparse_output=False)
model=encoder.fit_transform(df)
print(model)

[[0. 0.]
 [1. 0.]
 [0. 1.]
 [0. 0.]]


In [24]:
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

df=[
    [85,"M","verygood"],
    [95,"F","excellent"],
    [60,"M","good"],
    [80,np.nan,"avrage"],
    [70,"M","good"],
    [70,np.nan,"verygood"],
    [60,"F","verygood"],
    [98,"M","execellent"]
]
cols=["marks","gender","result"]
df2=pd.DataFrame(df,columns=cols)
print(df2)

model=SimpleImputer(missing_values=np.nan,strategy="most_frequent",fill_value="80")

result = df2["gender"].values.reshape(-1,1)
df2["gender"] = model.fit_transform(result).ravel()
print()
print(df2)

   marks gender      result
0     85      M    verygood
1     95      F   excellent
2     60      M        good
3     80    NaN      avrage
4     70      M        good
5     70    NaN    verygood
6     60      F    verygood
7     98      M  execellent

   marks gender      result
0     85      M    verygood
1     95      F   excellent
2     60      M        good
3     80      M      avrage
4     70      M        good
5     70      M    verygood
6     60      F    verygood
7     98      M  execellent
