<a href="https://colab.research.google.com/github/RamyaSri2222/Data-Science/blob/main/multiclass_classification_in_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving iris.csv to iris.csv


In [ ]:
import pandas as pd
df=pd.read_csv("iris.csv")
print(df)

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


In [ ]:
import pandas as pd
import numpy
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
df=pd.read_csv("iris.csv")
x=df.iloc[:,:4].values
y=df.iloc[:,4].values
lab=LabelEncoder()
y=lab.fit_transform(y)
y=to_categorical(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
model=Sequential()
model.add(Dense(16,input_shape=(4,),activation="relu"))
model.add(Dense(12,activation="relu"))
model.add(Dense(3,activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])
model.fit(x_train,y_train,epochs=100,batch_size=10,verbose=0)
print(model.predict(x_test))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
[[6.65410084e-07 8.26367065e-02 9.17362690e-01]
 [7.18380397e-06 2.80633718e-01 7.19359100e-01]
 [3.92587157e-03 9.55533385e-01 4.05407287e-02]
 [8.88428278e-03 9.83957767e-01 7.15794973e-03]
 [9.86813843e-01 1.31861018e-02 2.56277985e-08]
 [1.03349307e-09 7.40785478e-03 9.92592156e-01]
 [1.00498971e-06 1.35600328e-01 8.64398658e-01]
 [2.22360250e-03 9.64868367e-01 3.29080187e-02]
 [1.27939165e-06 1.06789023e-01 8.93209696e-01]
 [1.16141431e-03 9.44985747e-01 5.38528785e-02]
 [9.92335796e-01 7.66417710e-03 3.28923333e-09]
 [9.87594247e-01 1.24056898e-02 1.20215340e-08]
 [5.56004408e-04 8.72223318e-01 1.27220541e-01]
 [9.85571802e-01 1.44281341e-02 1.05668851e-08]
 [9.91344869e-01 8.65508709e-03 1.10331015e-08]
 [2.95832233e-05 5.24621069e-01 4.75349396e-01]
 [1.71176765e-07 5.50669767e-02 9.44932818e-01]
 [2.60943803e-03 9.89608228e-01 7.78234564e-03]
 [9.95877504e-01 4.12252173e-03 7.92641508e-10]
 [9.97309089e-01 2.69097718e-03 3.19438753e-10]
 [

In [ ]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
df=pd.read_csv("iris.csv")
x=df.iloc[:,:4].values
y=df.iloc[:,4].values
lab=LabelEncoder()
y=lab.fit_transform(y)
y=to_categorical(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
model=Sequential()
model.add(Dense(16,input_shape=(4,),activation="relu"))
model.add(Dense(12,activation="relu"))
model.add(Dense(3,activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])
model.fit(x_train,y_train,epochs=100,batch_size=10,verbose=0)
prediction=model.predict(x_test)
m=np.argmax(prediction,axis=1)
n=np.argmax(y_test,axis=1)
print(m)
print(n)
print(accuracy_score(m,n))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
[2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 1 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
[2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
0.9666666666666667
